backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"
display_url: https://lavamachine.com

collections: # A list of collections the CMS should be able to edit
- name: "pages"
  label: "Pages"
  files:
  - file: "site/content/_index.md"
    label: "Home Page"
    name: "home"
    fields:
    - {label: Title, name: title, widget: string}
    - {label: Subtitle, name: subtitle, widget: string}
    - {label: Image, name: image, widget: image}
    - {label: Welcome Text, name: welcomeBlurb, widget: object, fields: [
        {label: Heading, name: heading, widget: string},
        {label: Text, name: text, widget: text}]}
    - {label: Double Image, name: imageAndImage, widget: object, fields: [
        {label: Image Left, name: imagelefturl, widget: image},
        {label: Image Right, name: imagerighturl, widget: image}]}
    - {label: Headline, name: headlineBig, widget: object, fields: [
        {label: Headline, name: headline, widget: string}]}
    - {label: Icons with Text, name: textAndTextAndText, widget: object, fields: [
        {label: Item One, name: item1, widget: object, fields: [
          {label: Heading, name: heading, widget: string},
          {label: Text, name: text, widget: string},
          {label: Image, name: image, widget: image},
          {label: Button Text, name: buttontext, widget: string},
          {label: Button Url, name: buttonUrl, widget: string}]},
        {label: Item Two, name: item2, widget: object, fields: [
          {label: Heading, name: heading, widget: string},
          {label: Text, name: text, widget: string},
          {label: Image, name: image, widget: image},
          {label: Button Text, name: buttontext, widget: string},
          {label: Button Url, name: buttonUrl, widget: string}]},
        {label: Item Three, name: item3, widget: object, fields: [
          {label: Heading, name: heading, widget: string},
          {label: Text, name: text, widget: string},
          {label: Image, name: image, widget: image},
          {label: Button Text, name: buttontext, widget: string},
          {label: Button Url, name: buttonUrl, widget: string}]},
        {label: Small Images, name: images_are_small, widget: string}
    ]}
  - file: "site/content/about/_index.md"
    label: "About Page"
    name: "about"
    fields:
    - {label: Title, name: title, widget: string}
    - {label: Image, name: image, widget: image}
    - {label: Welcome Text, name: welcomeBlurb, widget: object, fields: [
        {label: Heading, name: heading, widget: string},
        {label: Text, name: text, widget: text}]}
    - {label: Headline, name: headlineBig, widget: object, fields: [
        {label: Headline, name: headline, widget: string}]}
    - {label: Images with Text, name: textAndText, widget: object, fields: [
        {label: Image Left, name: imageleft, widget: image},
        {label: Heading Left, name: headingleft, widget: string},
        {label: Subheadline Left, name: subheadingleft, widget: string},
        {label: Text Left, name: textleft, widget: text},
        {label: Image Right, name: imageright, widget: image},
        {label: Heading Right, name: headingright, widget: string},
        {label: Subheadline Right, name: subheadingright, widget: string},
        {label: Text Right, name: textright, widget: text}]}
  - file: "site/content/portfolio/_index.md"
    label: "Portfolio Page"
    name: "portfolio"
    fields:
    - {label: Title, name: title, widget: string}
    - {label: Image, name: image, widget: image}
    - {label: Special Video, name: videoSpecial, widget: object, fields: [
        {label: Headline, name: headline, widget: string},
        {label: Text, name: text, widget: text},
        {label: Display video on the right, name: reverse, widget: boolean}]}
    - {label: Video List, name: videoList, widget: object, fields: [
        {label: Video One, name: video1, widget: object, fields: [
          {label: Headline, name: headline, widget: string},
          {label: Text, name: text, widget: text},
          {label: Vimeo Video Number, name: vimeonummer, widget: number, valueType: int},
          {label: Display video on the right, name: reverse, widget: boolean}]},
        {label: Video Two, name: video2, widget: object, fields: [
          {label: Headline, name: headline, widget: string},
          {label: Text, name: text, widget: text},
          {label: Vimeo Video Number, name: vimeonummer, widget: number, valueType: int},
          {label: Display video on the right, name: reverse, widget: boolean}]},
        {label: Video Three, name: video3, widget: object, fields: [
          {label: Headline, name: headline, widget: string},
          {label: Text, name: text, widget: text},
          {label: Vimeo Video Number, name: vimeonummer, widget: number, valueType: int},
          {label: Display video on the right, name: reverse, widget: boolean}]},
        {label: Video Four, name: video4, widget: object, fields: [
          {label: Headline, name: headline, widget: string},
          {label: Text, name: text, widget: text},
          {label: Vimeo Video Number, name: vimeonummer, widget: number, valueType: int},
          {label: Display video on the right, name: reverse, widget: boolean}]},
        {label: Video Five, name: video5, widget: object, fields: [
          {label: Headline, name: headline, widget: string},
          {label: Text, name: text, widget: text},
          {label: Vimeo Video Number, name: vimeonummer, widget: number, valueType: int},
          {label: Display video on the right, name: reverse, widget: boolean}]},
        {label: Video Six, name: video6, widget: object, fields: [
          {label: Headline, name: headline, widget: string},
          {label: Text, name: text, widget: text},
          {label: Vimeo Video Number, name: vimeonummer, widget: number, valueType: int},
          {label: Display video on the right, name: reverse, widget: boolean}]},
        {label: Video Seven, name: video7, widget: object, fields: [
          {label: Headline, name: headline, widget: string},
          {label: Text, name: text, widget: text},
          {label: Vimeo Video Number, name: vimeonummer, widget: number, valueType: int},
          {label: Display video on the right, name: reverse, widget: boolean}]},
        {label: Video Eight, name: video8, widget: object, fields: [
          {label: Headline, name: headline, widget: string},
          {label: Text, name: text, widget: text},
          {label: Vimeo Video Number, name: vimeonummer, widget: number, valueType: int},
          {label: Display video on the right, name: reverse, widget: boolean}]},
        {label: Video Nine, name: video9, widget: object, fields: [
          {label: Headline, name: headline, widget: string},
          {label: Text, name: text, widget: text},
          {label: Vimeo Video Number, name: vimeonummer, widget: number, valueType: int},
          {label: Display video on the right, name: reverse, widget: boolean}]},
        {label: Video Ten, name: video10, widget: object, fields: [
          {label: Headline, name: headline, widget: string},
          {label: Text, name: text, widget: text},
          {label: Vimeo Video Number, name: vimeonummer, widget: number, valueType: int},
          {label: Display video on the right, name: reverse, widget: boolean}]}]}
  - file: "site/content/vr-live-painting/_index.md"
    label: "VR Live Painting Page"
    name: "vr-live-painting"
    fields:
    - {label: Title, name: title, widget: string}
    - {label: Image, name: image, widget: image}
    - {label: Welcome Text, name: welcomeBlurb, widget: object, fields: [
        {label: Heading, name: heading, widget: string},
        {label: Text, name: text, widget: text}]}
    - {label: Video List, name: videoList, widget: object, fields: [
        {label: Video One, name: video1, widget: object, fields: [
          {label: Headline, name: headline, widget: string},
          {label: Text, name: text, widget: text},
          {label: Vimeo Video Number, name: vimeonummer, widget: number, valueType: int},
          {label: Display video on the right, name: reverse, widget: boolean}]},
        {label: Video Two, name: video2, widget: object, fields: [
          {label: Headline, name: headline, widget: string},
          {label: Text, name: text, widget: text},
          {label: Vimeo Video Number, name: vimeonummer, widget: number, valueType: int},
          {label: Display video on the right, name: reverse, widget: boolean}]},
        {label: Video Three, name: video3, widget: object, fields: [
          {label: Headline, name: headline, widget: string},
          {label: Text, name: text, widget: text},
          {label: Vimeo Video Number, name: vimeonummer, widget: number, valueType: int},
          {label: Display video on the right, name: reverse, widget: boolean}]},
        {label: Video Four, name: video4, widget: object, fields: [
          {label: Headline, name: headline, widget: string},
          {label: Text, name: text, widget: text},
          {label: Vimeo Video Number, name: vimeonummer, widget: number, valueType: int},
          {label: Display video on the right, name: reverse, widget: boolean}]},
        {label: Video Five, name: video5, widget: object, fields: [
          {label: Headline, name: headline, widget: string},
          {label: Text, name: text, widget: text},
          {label: Vimeo Video Number, name: vimeonummer, widget: number, valueType: int},
          {label: Display video on the right, name: reverse, widget: boolean}]},
        {label: Video Six, name: video6, widget: object, fields: [
          {label: Headline, name: headline, widget: string},
          {label: Text, name: text, widget: text},
          {label: Vimeo Video Number, name: vimeonummer, widget: number, valueType: int},
          {label: Display video on the right, name: reverse, widget: boolean}]},
        {label: Video Seven, name: video7, widget: object, fields: [
          {label: Headline, name: headline, widget: string},
          {label: Text, name: text, widget: text},
          {label: Vimeo Video Number, name: vimeonummer, widget: number, valueType: int},
          {label: Display video on the right, name: reverse, widget: boolean}]},
        {label: Video Eight, name: video8, widget: object, fields: [
          {label: Headline, name: headline, widget: string},
          {label: Text, name: text, widget: text},
          {label: Vimeo Video Number, name: vimeonummer, widget: number, valueType: int},
          {label: Display video on the right, name: reverse, widget: boolean}]},
        {label: Video Nine, name: video9, widget: object, fields: [
          {label: Headline, name: headline, widget: string},
          {label: Text, name: text, widget: text},
          {label: Vimeo Video Number, name: vimeonummer, widget: number, valueType: int},
          {label: Display video on the right, name: reverse, widget: boolean}]},
        {label: Video Ten, name: video10, widget: object, fields: [
          {label: Headline, name: headline, widget: string},
          {label: Text, name: text, widget: text},
          {label: Vimeo Video Number, name: vimeonummer, widget: number, valueType: int},
          {label: Display video on the right, name: reverse, widget: boolean}]}
        ]}
    - {label: Headline, name: headlineBig, widget: object, fields: [
        {label: Headline, name: headline, widget: string}]}
    - {label: Images Grid, name: imagesGrid, widget: object, fields: [
        {label: Image One, name: image1, widget: object, fields: [
          {label: Image, name: image, widget: image},
          {label: Alt, name: alt, widget: string},
          {label: Text, name: text, widget: string}]},
        {label: Image Two, name: image2, widget: object, fields: [
          {label: Image, name: image, widget: image},
          {label: Alt, name: alt, widget: string},
          {label: Text, name: text, widget: string}]},
        {label: Image Three, name: image3, widget: object, fields: [
          {label: Image, name: image, widget: image},
          {label: Alt, name: alt, widget: string},
          {label: Text, name: text, widget: string}]},
        {label: Image Four, name: image4, widget: object, fields: [
          {label: Image, name: image, widget: image},
          {label: Alt, name: alt, widget: string},
          {label: Text, name: text, widget: string}]}]}
  - file: "site/content/contact/_index.md"
    label: "Contact Page"
    name: "contact"
    fields:
    - {label: Title, name: title, widget: string}
    - {label: Image, name: image, widget: image}
    - {label: Contact Info, name: contactData, widget: object, fields: [
        {label: Heading, name: heading, widget: string},
        {label: Name, name: name, widget: string},
        {label: Street, name: street, widget: string},
        {label: PLZ, name: plz, widget: string},
        {label: City, name: city, widget: string},
        {label: Country, name: country, widget: string},
        {label: Telephone, name: telephone, widget: string},
        {label: Email, name: email, widget: string}]}
  - file: "site/content/workshop/_index.md"
    label: "Workshop Page"
    name: "workshop"
    fields:
    - {label: Title, name: title, widget: string}
    - {label: Image, name: image, widget: image}
    - {label: Welcome Text, name: welcomeBlurb, widget: object, fields: [
        {label: Heading, name: heading, widget: string},
        {label: Text, name: text, widget: text}]}
    - {label: Double Image, name: imageAndImage, widget: object, fields: [
        {label: Image Left, name: imagelefturl, widget: image},
        {label: Image Right, name: imagerighturl, widget: image}]}
    - {label: Headline, name: headlineBig, widget: object, fields: [
        {label: Headline, name: headline, widget: string}]}
    - {label: Icons with Text, name: textAndTextAndText, widget: object, fields: [
        {label: Item One, name: item1, widget: object, fields: [
        {label: Heading, name: heading, widget: string},
        {label: Text, name: text, widget: string},
        {label: Image, name: image, widget: image},
        {label: Button Text, name: buttontext, widget: string},
        {label: Button Url, name: buttonUrl, widget: string}]},
        {label: Item Two, name: item2, widget: object, fields: [
        {label: Heading, name: heading, widget: string},
        {label: Text, name: text, widget: string},
        {label: Image, name: image, widget: image},
        {label: Button Text, name: buttontext, widget: string},
        {label: Button Url, name: buttonUrl, widget: string}]},
        {label: Item Three, name: item3, widget: object, fields: [
        {label: Heading, name: heading, widget: string},
        {label: Text, name: text, widget: string},
        {label: Image, name: image, widget: image},
        {label: Button Text, name: buttontext, widget: string},
        {label: Button Url, name: buttonUrl, widget: string}]},
        {label: Small Images, name: images_are_small, widget: string}]}
  - file: "site/content/data-protection/_index.md"
    label: "Data Protection"
    name: "data-protection"
    fields:
    - {label: Title, name: heading, widget: string}
    - {label: Content, name: body, widget: markdown}
  - file: "site/content/imprint/_index.md"
    label: "Imprint"
    name: "imprint"
    fields:
    - {label: Title, name: heading, widget: string}
    - {label: Content, name: body, widget: markdown}
