backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
- name: "pages"
  label: "Pages"
  files:
  - file: "site/content/_index.md"
    label: "Home Page"
    name: "home"
    fields:
    - {label: Title, name: title, widget: string}
    - {label: Subtitle, name: subtitle, widget: string}
    - {label: Image, name: image, widget: image}
    - {label: Welcome Text, name: welcomeBlurb, widget: object, fields: [
        {label: Heading, name: heading, widget: string},
        {label: Text, name: text, widget: text}]}
    - {label: Double Image, name: imageAndImage, widget: object, fields: [
        {label: Image Left, name: imagelefturl, widget: image},
        {label: Image Right, name: imagerighturl, widget: image}]}
    - {label: Headline, name: headlineBig, widget: object, fields: [
        {label: Headline, name: headline, widget: string}]}
    - {label: Icons with Text, name: textAndTextAndText, widget: object, fields: [
        {label: Item One, name: item1, widget: object, fields: [
          {label: Heading, name: heading, widget: string},
          {label: Text, name: text, widget: string},
          {label: Image, name: image, widget: image},
          {label: Button Text, name: buttontext, widget: string},
          {label: Button Url, name: buttonUrl, widget: string}]},
        {label: Item Two, name: item2, widget: object, fields: [
          {label: Heading, name: heading, widget: string},
          {label: Text, name: text, widget: string},
          {label: Image, name: image, widget: image},
          {label: Button Text, name: buttontext, widget: string},
          {label: Button Url, name: buttonUrl, widget: string}]},
        {label: Item Three, name: item3, widget: object, fields: [
          {label: Heading, name: heading, widget: string},
          {label: Text, name: text, widget: string},
          {label: Image, name: image, widget: image},
          {label: Button Text, name: buttontext, widget: string},
          {label: Button Url, name: buttonUrl, widget: string}]},
        {label: Small Images, name: images_are_small, widget: string}
    ]}        
  - file: "site/content/about/_index.md"
    label: "About Page"
    name: "about"
    fields:
    - {label: Title, name: title, widget: string}
    - {label: Image, name: image, widget: image}
    - {label: Welcome Text, name: welcomeBlurb, widget: object, fields: [
        {label: Heading, name: heading, widget: string},
        {label: Text, name: text, widget: text}]}
    - {label: Headline, name: headlineBig, widget: object, fields: [
        {label: Headline, name: headline, widget: string}]}
    - {label: Images with Text, name: textAndText, widget: object, fields: [
        {label: Image Left, name: imageleft, widget: image},
        {label: Heading Left, name: headingleft, widget: string},
        {label: Subheadline Left, name: subheadingleft, widget: string},
        {label: Text Left, name: textleft, widget: text},
        {label: Image Right, name: imageright, widget: image},
        {label: Heading Right, name: headingright, widget: string},
        {label: Subheadline Right, name: subheadingright, widget: string},
        {label: Text Right, name: textright, widget: text}]}
  - file: "site/content/portfolio/_index.md"
    label: "Portfolio Page"
    name: "portfolio"
    fields:
    - {label: Title, name: title, widget: string}
    - {label: Image, name: image, widget: image}
    - {label: Video One, name: video_one, widget: object, fields: [
        {label: Headline, name: headline, widget: string},
        {label: Text, name: text, widget: text},
        {label: Vimeo Video Number, name: vimeonummer, widget: string}]}
    - {label: Video Two, name: video_two, widget: object, fields: [
        {label: Headline, name: headline, widget: string},
        {label: Text, name: text, widget: text},
        {label: Vimeo Video Number, name: vimeonummer, widget: string}]}
    - {label: Video Three, name: video_three, widget: object, fields: [
        {label: Headline, name: headline, widget: string},
        {label: Text, name: text, widget: text},
        {label: Vimeo Video Number, name: vimeonummer, widget: string}]}
  - file: "site/content/vr-live-painting/_index.md"
    label: "VR Live Painting Page"
    name: "vr-live-painting"
    fields:
    - {label: Title, name: title, widget: string}
    - {label: Image, name: image, widget: image}
    - {label: Welcome Text, name: welcomeBlurb, widget: object, fields: [
        {label: Heading, name: heading, widget: string},
        {label: Text, name: text, widget: text}]}
    - {label: Video One, name: video_one, widget: object, fields: [
        {label: Headline, name: headline, widget: string},
        {label: Text, name: text, widget: text},
        {label: Vimeo Video Number, name: vimeonummer, widget: string}]}
    - {label: Video Two, name: video_two, widget: object, fields: [
        {label: Headline, name: headline, widget: string},
        {label: Text, name: text, widget: text},
        {label: Vimeo Video Number, name: vimeonummer, widget: string}]}
    - {label: Headline, name: headlineBig, widget: object, fields: [
        {label: Headline, name: headline, widget: string}]}
    - {label: Images Grid, name: imagesGrid, widget: object, fields: [
        {label: Image One, name: image1, widget: object, fields: [
          {label: Image, name: image, widget: image},
          {label: Alt, name: alt, widget: string},
          {label: Text, name: text, widget: string}]},
        {label: Image Two, name: image2, widget: object, fields: [
          {label: Image, name: image, widget: image},
          {label: Alt, name: alt, widget: string},
          {label: Text, name: text, widget: string}]},
        {label: Image Three, name: image3, widget: object, fields: [
          {label: Image, name: image, widget: image},
          {label: Alt, name: alt, widget: string},
          {label: Text, name: text, widget: string}]},
        {label: Image Four, name: image4, widget: object, fields: [
          {label: Image, name: image, widget: image},
          {label: Alt, name: alt, widget: string},
          {label: Text, name: text, widget: string}]}
    ]}
